default: &default
  adapter: postgresql
  encoding: unicode
  # username: etg
  # password: immortal
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: schoolzy_development

test:
  <<: *default
  database: schoolzy_test

production:
  <<: *default
  database: schoolzy_production
  username: schoolzy
  password: <%= ENV["SCHOOLZY_DATABASE_PASSWORD"] %>
